make:
	clang++ zad1.cpp -o zad1.out -Wall -Wextra --std=c++17
	clang++ zad2.cpp -o zad2.out -Wall -Wextra --std=c++17
	clang++ zad3.cpp -o zad3.out -Wall -Wextra --std=c++17
	clang++ zad4.cpp -o zad4.out -Wall -Wextra --std=c++17
	clang++ zad5.cpp -o zad5.out -Wall -Wextra --std=c++17